########################################
# 🎄 Day -1: Get your winter boots on! #
########################################

### ⭐ Task 1: Everything is OK
GET http://localhost:8000/

### 🎁 Task 2: Fake error
GET http://localhost:8000/-1/error

###############################################
# 🎄 Day 1: Packet "exclusive-cube" not found #
###############################################

### ⭐ Task 1: Cube the bits
GET http://localhost:8000/1/4/8

### 🎁 Task 2: The sled ID system
GET http://localhost:8000/1/4/5/8/10

##############################################################
# 🎄 Day 4: What do you call a serialized reindeer? Serdeer! #
##############################################################

### ⭐ Task 1: Reindeer cheer
POST http://localhost:8000/4/strength
content-type: application/json

[
    { "name": "Dasher", "strength": 5 },
    { "name": "Dancer", "strength": 6 },
    { "name": "Prancer", "strength": 4 },
    { "name": "Vixen", "strength": 7 }
]

### 🎁 Task 2: Cursed candy eating contest 
POST http://localhost:8000/4/contest
content-type: application/json

[
    {
      "name": "Dasher",
      "strength": 5,
      "speed": 50.4,
      "height": 80,
      "antler_width": 36,
      "snow_magic_power": 9001,
      "favorite_food": "hay",
      "cAnD13s_3ATeN-yesT3rdAy": 2
    },
    {
      "name": "Dancer",
      "strength": 6,
      "speed": 48.2,
      "height": 65,
      "antler_width": 37,
      "snow_magic_power": 4004,
      "favorite_food": "grass",
      "cAnD13s_3ATeN-yesT3rdAy": 5
    }
]

############################
# 🎄 Day 6: Elf on a shelf #
############################

### ⭐ Task 1: Never count on an elf
POST http://localhost:8000/6
content-type: text/plain

"The mischievous elf peeked out from behind the toy workshop,
and another elf joined in the festive dance.
Look, there is also an elf on that shelf!"

### ⭐ Task 2: Shelf under an elf?
POST http://localhost:8000/6
content-type: text/plain

"there is an elf on a shelf on an elf.
there is also another shelf in Belfast."

####################################
# 🎄 Day 7: GET Santa some cookies #
####################################

### ⭐ Task 1: Based encoding, 64th edition
GET http://localhost:8000/7/decode
Cookie: recipe=eyJmbG91ciI6MTAwLCJjaG9jb2xhdGUgY2hpcHMiOjIwfQ==

### 🎁 Task 2: The secret cookie recipe
GET http://localhost:8000/7/bake
Cookie: recipe=eyJyZWNpcGUiOnsiZmxvdXIiOjk1LCJzdWdhciI6NTAsImJ1dHRlciI6MzAsImJha2luZyBwb3dkZXIiOjEwLCJjaG9jb2xhdGUgY2hpcHMiOjUwfSwicGFudHJ5Ijp7ImZsb3VyIjozODUsInN1Z2FyIjo1MDcsImJ1dHRlciI6MjEyMiwiYmFraW5nIHBvd2RlciI6ODY1LCJjaG9jb2xhdGUgY2hpcHMiOjQ1N319

### Task 3: Questionable cookie recipes
GET http://localhost:8000/7/bake
Cookie: recipe=eyJyZWNpcGUiOnsic2xpbWUiOjl9LCJwYW50cnkiOnsiY29iYmxlc3RvbmUiOjY0LCJzdGljayI6IDR9fQ==

####################################
# 🎄 Day 8: GET Santa some cookies #
####################################

### Test Pokemon Graphql API
POST https://graphqlpokemon.favware.tech/v8
content-type: application/json

{
  "query": "query GetPokemonByDexNumber($number: Int!) { getPokemonByDexNumber(number: $number) {key num weight}}",
  "variables": {"number": 25}
}

### ⭐ Task 1: IT'S PIKACHU!
GET http://localhost:8000/8/weight/25

### 🎁 Task 2: That's gonna leave a dent
GET http://localhost:8000/8/drop/25
