########################################
# 🎄 Day -1: Get your winter boots on! #
########################################

### ⭐ Task 1: Everything is OK
GET http://localhost:8000/

### 🎁 Task 2: Fake error
GET http://localhost:8000/-1/error

###############################################
# 🎄 Day 1: Packet "exclusive-cube" not found #
###############################################

### ⭐ Task 1: Cube the bits
GET http://localhost:8000/1/4/8

### 🎁 Task 2: The sled ID system
GET http://localhost:8000/1/4/5/8/10

##############################################################
# 🎄 Day 4: What do you call a serialized reindeer? Serdeer! #
##############################################################

### ⭐ Task 1: Reindeer cheer
POST http://localhost:8000/4/strength
content-type: application/json

[
    { "name": "Dasher", "strength": 5 },
    { "name": "Dancer", "strength": 6 },
    { "name": "Prancer", "strength": 4 },
    { "name": "Vixen", "strength": 7 }
]

### 🎁 Task 2: Cursed candy eating contest 
POST http://localhost:8000/4/contest
content-type: application/json

[
    {
      "name": "Dasher",
      "strength": 5,
      "speed": 50.4,
      "height": 80,
      "antler_width": 36,
      "snow_magic_power": 9001,
      "favorite_food": "hay",
      "cAnD13s_3ATeN-yesT3rdAy": 2
    },
    {
      "name": "Dancer",
      "strength": 6,
      "speed": 48.2,
      "height": 65,
      "antler_width": 37,
      "snow_magic_power": 4004,
      "favorite_food": "grass",
      "cAnD13s_3ATeN-yesT3rdAy": 5
    }
]
### extra test
POST http://localhost:8000/4/contest
content-type: application/json

[
    {
        "name": "Comet",
        "strength": 29,
        "speed": 42.378589917764984,
        "height": 59,
        "antler_width": 20,
        "snow_magic_power": 4796,
        "favorite_food": "grass",
        "cAnD13s_3ATeN-yesT3rdAy": 2
    },
    {
        "name": "Blitzen",
        "strength": 20,
        "speed": 34.03420136230174,
        "height": 59,
        "antler_width": 39,
        "snow_magic_power": 1387,
        "favorite_food": "leaves",
        "cAnD13s_3ATeN-yesT3rdAy": 9
    },
    {
        "name": "Donner",
        "strength": 14,
        "speed": 39.49874839731527,
        "height": 66,
        "antler_width": 41,
        "snow_magic_power": 1776,
        "favorite_food": "berries",
        "cAnD13s_3ATeN-yesT3rdAy": 6
    }
]

### result
{
    "fastest": "Speeding past the finish line with a strength of 29 is Comet",
    "tallest": "Donner is standing tall with his 41 cm wide antlers",
    "magician": "Comet could blast you away with a snow magic power of 4796",
    "consumer": "Blitzen ate lots of candies, but also some leaves"
}

############################
# 🎄 Day 6: Elf on a shelf #
############################

### ⭐ Task 1: Never count on an elf
POST http://localhost:8000/6
content-type: text/plain

"The mischievous elf peeked out from behind the toy workshop,
and another elf joined in the festive dance.
Look, there is also an elf on that shelf!"

### ⭐ Task 2: Shelf under an elf?
POST http://localhost:8000/6
content-type: text/plain

"there is an elf on a shelf on an elf.
there is also another shelf in Belfast."

####################################
# 🎄 Day 7: GET Santa some cookies #
####################################

### ⭐ Task 1: Based encoding, 64th edition
GET http://localhost:8000/7/decode
Cookie: recipe=eyJmbG91ciI6MTAwLCJjaG9jb2xhdGUgY2hpcHMiOjIwfQ==

### 🎁 Task 2: The secret cookie recipe
GET http://localhost:8000/7/bake
Cookie: recipe=eyJyZWNpcGUiOnsiZmxvdXIiOjk1LCJzdWdhciI6NTAsImJ1dHRlciI6MzAsImJha2luZyBwb3dkZXIiOjEwLCJjaG9jb2xhdGUgY2hpcHMiOjUwfSwicGFudHJ5Ijp7ImZsb3VyIjozODUsInN1Z2FyIjo1MDcsImJ1dHRlciI6MjEyMiwiYmFraW5nIHBvd2RlciI6ODY1LCJjaG9jb2xhdGUgY2hpcHMiOjQ1N319

### Task 3: Questionable cookie recipes
GET http://localhost:8000/7/bake
Cookie: recipe=eyJyZWNpcGUiOnsic2xpbWUiOjl9LCJwYW50cnkiOnsiY29iYmxlc3RvbmUiOjY0LCJzdGljayI6IDR9fQ==

#########################
# 🎄 Day 8: PokéPhysics #
#########################

### Test Pokemon Graphql API
POST https://graphqlpokemon.favware.tech/v8
content-type: application/json

{
  "query": "query GetPokemonByDexNumber($number: Int!) { getPokemonByDexNumber(number: $number) {key num weight}}",
  "variables": {"number": 25}
}

### ⭐ Task 1: IT'S PIKACHU!
GET http://localhost:8000/8/weight/25

### 🎁 Task 2: That's gonna leave a dent
GET http://localhost:8000/8/drop/25

##########################################
# 🎄 Day 11: Imagery from the North Pole #
##########################################

### ⭐ Task 1: Served on a silver platter
GET http://localhost:8000/11/assets/decoration.png

### 🎁 Task 2: Bull mode activated 
POST http://localhost:8000/11/red_pixels
content-type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="image"; filename="decoration.png"
Content-Type: image/png

< ./assets/decoration.png
------WebKitFormBoundary--

#########################
# 🎄 Day 12: Timekeeper #
#########################

### ⭐ Task 1: How To Time Persist?
POST http://localhost:8000/12/save/packet20231212

###
GET http://localhost:8000/12/load/packet20231212

##################################
# 🎄 Day 13: Santa's Gift Orders #
##################################

### ⭐ Task 1: SQL? Sequel? Squeel??
GET curl http://localhost:8000/13/sql

### ⭐ Task 2: Use code NorthPole2023 for 2023% off???
POST http://localhost:8000/13/reset
###
POST http://localhost:8000/13/orders
Content-Type: application/json'

[
    {"id":1,"region_id":2,"gift_name":"Toy Train","quantity":5},
    {"id":2,"region_id":2,"gift_name":"Doll","quantity":8},
    {"id":3,"region_id":3,"gift_name":"Action Figure","quantity":12},
    {"id":4,"region_id":4,"gift_name":"Board Game","quantity":10},
    {"id":5,"region_id":2,"gift_name":"Teddy Bear","quantity":6},
    {"id":6,"region_id":3,"gift_name":"Toy Train","quantity":3}
]

###
GET http://localhost:8000/13/orders/total

### 🎁 Task 3: Truly one of the gifts of all time
POST http://localhost:8000/13/reset

###
POST http://localhost:8000/13/orders
Content-Type: application/json'

[
    {"id":1,"region_id":2,"gift_name":"Toy Train","quantity":5},
    {"id":2,"region_id":2,"gift_name":"Doll","quantity":8},
    {"id":3,"region_id":3,"gift_name":"Toy Train","quantity":4}
  ]'

###
GET http://localhost:8000/13/orders/popular

###############################
# 🎄 Day 14: Reindeering HTML #
###############################

### ⭐ Task 1: Ho-ho, Toymaking Magic Land! (HTML)
POST http://localhost:8000/14/unsafe
Content-Type: application/json

{"content": "<h1>Welcome to the North Pole!</h1>"}

### 🎁 Task 2: Safety 2nd
POST http://localhost:8000/14/safe
Content-Type: application/json

{"content": "<script>alert(\"XSS Attack!\")</script>"}
